enable and disable SUPPORT_URL with environment variable
openedx/frontend-component-header pull request #276
Opened 2022-11-05 17:22 UTC by isankadn

Description:

On the MFE learning top menu, the "Help" link is currently displayed by default.

With this change, the "Help" menu will only be visible if the environment contains the "SUPPORT URL" variable.

2022-11-05 17:23 UTC, openedx-webhooks commented
Thanks for the pull request, @isankadn!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

<!-- comment:no_cla -->


<!-- comment:external_pr -->
<!-- data: eyJkcmFmdCI6IGZhbHNlfQ== -->

2022-11-07 12:40 UTC, arbrandes requested changes
Thanks @isankadn!  I haven't actually tested this yet, but in the meantime, can you please:

* Add SUPPORT_URL to the `.env*` files
* Add an explanation of what this does to this repo's README?

2022-11-09 01:29 UTC, isankadn commented
@arbrandes  Thank you very much!
Both items are now completed!

2022-11-29 15:30 UTC, DeanJayMathew commented
Thanks for helping @arbrandes !

2022-11-30 12:31 UTC, arbrandes commented
@isankadn, thanks!

However, it looks like we're failing some tests.  Can you look into it?

Also, please refer to the automated message above: we need you to sign the CLA before accepting your code.  Mind doing that?  Thanks!

2022-12-01 06:58 UTC, isankadn commented
@arbrandes Thank you for your comment, sure I can sign. and the same time, I'm representing ABC for this, I think @DeanJayMathew has already taken care of that. 

and I will look into this error as well. thx. 

> Also, please refer to the automated message above: we need you to sign the CLA before accepting your code. Mind doing that? Thanks!

2022-12-01 06:58 UTC, isankadn commented
@arbrandes Thank you for your comment, sure I can sign. and the same time, I'm representing ABC for this, I think @DeanJayMathew has already taken care of that. 

and I will look into this error as well. thx. 

> Also, please refer to the automated message above: we need you to sign the CLA before accepting your code. Mind doing that? Thanks!

2022-12-01 07:41 UTC, isankadn commented
@arbrandes fixed the linting issue. and pushed.

2023-01-06 18:42 UTC, mphilbrick211 commented
Hi @isankadn! Just following up on this PR. In order to push it through, you'll need to complete a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base). Please let me know if you have any questions.

2023-01-11 01:37 UTC, mphilbrick211 commented
Hi @isankadn! Tests have been enabled for this pull request, though you'll still need to fill out a [CLA form](https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base). Please let us know if you plan to pursue this pull request. Thanks!

2023-01-11 02:02 UTC, DeanJayMathew commented
Hi @Michelle Philbrick ***@***.***>

Thank you for following up on this.

@Isanka Wijerathne ***@***.***> (
https://github.com/isankadn, ***@***.***) should be covered under
the organisational contributors agreement I signed on behalf of ABC ONLINE
COURSES LIMITED.

Dean Jay Mathew
Director, ABC Online Courses Limited

Trusted Open edX® Service Providers since 2015
Schedule a meeting with me: https://calendly.com/abconlinecourses
View Our Website <http://www.abconlinecourses.com>
Tel.: +441225293341
Registered Address: Chestnut House
***@***.***,-2.1459131,15z/data=!3m1!4b1!4m8!1m2!2m1!1schestnut+house+53d+beanacre+sn127py!3m4!1s0x48717c9105a9d3d7:0x15804f821ad57207!8m2!3d51.3980641!4d-2.1374675>
(Wiltshire, England, UK)



*Legal Disclaimer: **This email and any files transmitted with it are
confidential and intended solely for the use of the individual or entity to
whom they are addressed and intended. If you have received this email in
error please notify the sender or system manager immediately. This message
contains confidential information and is intended only for the individual
named. If you are not the named addressee you should not disseminate,
distribute or copy this e-mail. Please notify the sender immediately by
e-mail if you have received this e-mail by mistake and delete this e-mail
from your system. If you are not the intended recipient you are notified
that disclosing, copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited.*



On Wed, Jan 11, 2023 at 8:38 AM Michelle Philbrick ***@***.***>
wrote:

> Hi @isankadn <https://github.com/isankadn>! Tests have been enabled for
> this pull request, though you'll still need to fill out a CLA form
> <https://openedx.atlassian.net/wiki/spaces/COMM/pages/941457737/How+to+start+contributing+to+the+Open+edX+code+base>.
> Please let us know if you plan to pursue this pull request. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openedx/frontend-component-header/pull/276#issuecomment-1378129613>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACMGDW6QAMVOXC24ZKGVGZ3WRYFIFANCNFSM6AAAAAARYAOAWU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-01-11 22:04 UTC, mphilbrick211 commented
Thanks @DeanJayMathew! I'm not seeing @isankadn listed on our end. Let me follow-up internally to make sure I'm not missing anything.

2023-01-20 22:22 UTC, e0d commented
@mphilbrick211 I see him in the CLA file now.

@isankadn I also notice there are some commit lint issues, we use conventional commits as defined here: https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type

2023-01-23 20:36 UTC, mphilbrick211 commented
Hi @isankadn! Just flagging Ed's comment and Adolfo's requested changes. Also, your CLA should be all set now, so once tests are re-run the check should turn green.

2023-01-24 13:56 UTC, arbrandes requested changes

2023-01-24 13:56 UTC, arbrandes commented on src/learning-header/AuthenticatedUserDropdown.jsx
> +  );
I don't think we need to specify a separate variable for this.  It's fine if we just do it  below, via:

```
{getConfig().SUPPORT_URL && (
  <a>...</a>
)}

2023-01-24 13:57 UTC, arbrandes commented
@isankadn after you address my request, can you please squash your commits into a single one with a conventional commit title?  In this case it would be a `feat:`.

2023-02-07 22:16 UTC, mphilbrick211 commented
Hi @isankadn! Just checking in on this to see if you've been able to address Adolfo's feedback. Please let us know when this is ready to review. Thank you!

2023-02-24 03:12 UTC, mphilbrick211 commented
> Hi @isankadn! Just checking in on this to see if you've been able to address Adolfo's feedback. Please let us know when this is ready to review. Thank you!

Hi @isankadn! Just checking in to see if you are able to re-run the failing tests and confirm if the requested changes have been made. Thanks!

2023-03-24 21:21 UTC, mphilbrick211 commented
> > Hi @isankadn! Just checking in on this to see if you've been able to address Adolfo's feedback. Please let us know when this is ready to review. Thank you!
> 
> Hi @isankadn! Just checking in to see if you are able to re-run the failing tests and confirm if the requested changes have been made. Thanks!

Hi @isankadn friendly ping on this. Are you planning to pursue this PR?

2023-04-04 01:52 UTC, mphilbrick211 commented
Hi @isankadn - just checking in to see if you plan to pursue this pull request - please let us know. Thanks!

2023-04-25 00:29 UTC, mphilbrick211 commented
Hi @isankadn - I'm going to close this pull request for now. We can reopen if you'd like to pursue in the future. Thanks!

2023-04-25 00:29 UTC, closed without merging

2023-04-25 00:29 UTC, openedx-webhooks commented
@isankadn Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-component-header&entry.867055334=https://github.com/openedx/frontend-component-header/pull/276&entry.1484655318=https://github.com/isankadn&entry.752974735=2022-11-05+17:22&entry.1917517419=2023-04-25+00:29&entry.2133058324=No) so we can improve your experience in the future.

<!-- comment:end_survey -->
<!-- data: eyJqaXJhLXByZS1jbG9zZSI6IG51bGx9 -->