Sundas/inf 878
openedx/frontend-component-header pull request #350
Opened 2023-06-15 09:03 UTC by sundasnoreen12

**Description**
Add unit tests for notifications redux, selectors and API

1. Add Factory for 
    a. Notifications Count
    b. Notification List

2. API test cases
    a. successfully get notification counts for different tabs
    b. failed to get notification counts
    c. denied to get notification counts
    d. successfully get notifications
    e. failed to get notifications
    f. denied to get notifications
    g. successfully marked all notifications as seen for selected app
    h. failed to mark all notifications as seen for selected app
    i. denied to mark all notifications as seen for selected app
    j. successfully marked all notifications as read for selected app
    k. failed to mark all notifications as read for selected app
    l. denied to mark all notifications as read for selected app
    m. successfully marked notification as read 
    n. failed to mark notification as read 
    o. denied to mark notification as read

3. Add test cases for following selectors:
    a. should return notification status
    b. should return notification tabs count
    c. should return notification tabs
    d. should return selected app notification ids
    e. should return show notification tray status
    f. should return notifications
    g. should return notifications from Ids
    h. should return selected app name
    i. should return pagination data.

4. Redux test cases
    a. Successfully loaded initial notification states in redux
    b. Successfully loaded notifications list in the redux
    c. Successfully loaded notification counts in the redux
    d. Successfully loaded showNotificationTray status in the redux based on api
    e. Successfully store the count, numPages, currentPage, and nextPage data in redux
    f. Successfully updated the selected app name in redux
    g. Successfully store notification ids in the selected app in apps
    h. successfully marked all notifications as seen for selected app
    i. successfully marked all notifications as read for selected app in the redux.
    j. successfully marked notification as read in the redux.
    
    **Tested**
  Npm run test

2023-06-16 11:05 UTC, awais-ansari requested changes

2023-06-16 11:05 UTC, awais-ansari commented on src/Notifications/data/redux.test.js
> +    expect(apps.discussions).toHaveLength(2);
redundant test cases.

2023-06-19 11:20 UTC, ayesha-waris approved these changes

2023-06-19 11:49 UTC, awais-ansari requested changes

2023-06-19 11:49 UTC, awais-ansari commented on src/Notifications/data/api.js
> +export const markAllNotificationsAsReadpiUrl = () => `${getConfig().LMS_BASE_URL}/api/notifications/read/`;
nit: markAllNotificationsAsReadpiUrl. Spell mistake.

2023-06-19 11:49 UTC, awais-ansari commented on src/Notifications/data/api.js
> +export const markAllNotificationsAsReadpiUrl = () => `${getConfig().LMS_BASE_URL}/api/notifications/read/`;
Its name should be markNotificationAsReadApiUrl because some URL will also use to mark a single notification as read.

2023-06-19 11:49 UTC, awais-ansari commented on src/Notifications/data/api.test.js
> +  });
duplicate test case as the API URL is the same, the response will be the same.

2023-06-19 12:03 UTC, awais-ansari approved these changes

2023-06-19 12:10 UTC, merged