fix: clicking on notification redirecting to correct URL
openedx/frontend-component-header pull request #370
Opened 2023-07-12 12:48 UTC by ayesha-waris

[INF-951](https://2u-internal.atlassian.net/browse/INF-951)

#### Description

In frontend-component-header, when clicking on a notification, it was redirectsing to the wrong URL, which is fixed in this PR

2023-07-12 13:07 UTC, muhammadadeeltajamul requested changes

2023-07-12 13:07 UTC, muhammadadeeltajamul commented on src/Notifications/NotificationRowItem.jsx
> +      onClick={() => handleMarkAsRead}
onClick={handleMarkAsRead}

2023-07-13 10:42 UTC, awais-ansari requested changes

2023-07-13 10:42 UTC, awais-ansari commented on src/Notifications/NotificationRowItem.jsx
> +      rel="noreferrer"
rel="noopener noreferrer"

2023-07-13 11:09 UTC, awais-ansari approved these changes

2023-07-14 03:52 UTC, muhammadadeeltajamul approved these changes

2023-07-14 08:04 UTC, merged