refactor: update README File
openedx/frontend-component-header pull request #380
Opened 2023-08-04 09:49 UTC by Mashal-m

2023-09-25 06:08 UTC, BilalQamar95 approved these changes

2023-09-25 10:24 UTC, BilalQamar95 approved these changes

2023-10-04 06:53 UTC, abdullahwaheed requested changes

2023-10-04 06:53 UTC, abdullahwaheed commented on README.rst
> +    ``cd frontend-component-header && npm install``
```suggestion
    ``cd frontend-component-header && npm ci``
```

2023-10-04 07:29 UTC, abdullahwaheed approved these changes

2023-10-04 07:29 UTC, merged